Update setup.py
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\vmadmin\AppData\Local\Temp\2\pip-install-hparnyv1\remotely_fb4493aba776423faf31d999ff0e7754\setup.py", line 18
          print version
          ^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output]